In [1]:
import pandas as pd
import numpy as np

In [2]:
total_people=pd.read_csv("gender_submission.csv")
total_people.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [3]:
total_people.shape

(418, 2)

In [4]:
test=pd.read_csv("test.csv")
print(test.head())
test.shape

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

(418, 11)

In [5]:
train=pd.read_csv("train.csv")
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
train.shape

(891, 12)

In [7]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
train = train.drop(['PassengerId', 'Pclass','Name',  
                    'SibSp', 'Parch', 'Ticket', 'Fare', 
                    'Cabin', 'Embarked'], axis=1)

In [10]:
train.shape

(891, 3)

In [11]:
test=test.drop(['PassengerId', 'Pclass','Name',  
                    'SibSp', 'Parch', 'Ticket', 'Fare', 
                    'Cabin', 'Embarked'], axis=1)

In [12]:
test.shape

(418, 2)

In [13]:
train.head()

   Survived     Sex   Age
0         0    male  22.0
1         1  female  38.0
2         1  female  26.0
3         1  female  35.0
4         0    male  35.0

In [14]:
train['Sex'] = train['Sex'].replace({'male': 1, 'female': 0})

/var/folders/7q/j3s102ss7vl83m5y390b5gph0000gn/T/ipykernel_34086/955660753.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['Sex'] = train['Sex'].replace({'male': 1, 'female': 0})

In [15]:
train.head()

   Survived  Sex   Age
0         0    1  22.0
1         1    0  38.0
2         1    0  26.0
3         1    0  35.0
4         0    1  35.0

In [16]:
train.isnull().sum()

Survived      0
Sex           0
Age         177
dtype: int64

In [17]:
print(train['Age'].mean())

29.69911764705882

In [18]:
train['Age'] = train['Age'].fillna(train['Age'].mean())

In [19]:
train.isnull().sum()

Survived    0
Sex         0
Age         0
dtype: int64

In [20]:
test.head()

      Sex   Age
0    male  34.5
1  female  47.0
2    male  62.0
3    male  27.0
4  female  22.0

In [21]:
test['Sex'] = test['Sex'].replace({'male': 1, 'female': 0})

/var/folders/7q/j3s102ss7vl83m5y390b5gph0000gn/T/ipykernel_34086/1971732509.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['Sex'] = test['Sex'].replace({'male': 1, 'female': 0})

In [22]:
test.isnull().sum()

Sex     0
Age    86
dtype: int64

In [23]:
test['Age'] = test['Age'].fillna(test['Age'].mean())

In [24]:
test.isnull().sum()

Sex    0
Age    0
dtype: int64

In [25]:
X = train.drop('Survived', axis=1)
y = train['Survived']

In [26]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42)

In [29]:
model = SVC()
model.fit(X, y)

SVC()

In [30]:
y_pred = model.predict(X_test)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [31]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.4134078212290503

In [32]:
model2=DecisionTreeClassifier()
model2.fit(X,y)

DecisionTreeClassifier()

In [33]:
y_pred2=model2.predict(X_test)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [34]:
accuracy = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy)

Accuracy: 0.4134078212290503

In [35]:
model3=RandomForestClassifier()
model3.fit(X,y)

RandomForestClassifier()

In [36]:
y_pred3=model3.predict(X_test)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [37]:
accuracy = accuracy_score(y_test, y_pred3)
print("Accuracy:", accuracy)

Accuracy: 0.4134078212290503

In [38]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, y)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:738: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

SGDClassifier(max_iter=5)

In [39]:
g_pred=clf.predict(X_test)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(

In [40]:
accuracy = accuracy_score(y_test, g_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7821229050279329

In [ ]:
%pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 547.9 kB/s eta 0:00:00a 0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [42]:
import xgboost as xgb
from xgboost import XGBClassifier

In [44]:
params = {
    'objective':'binary:logistic',
    'max_depth':4,
    'learning_rate':0.1,
    'n_estimators':100,
    'alpha':10
}

model_xg = XGBClassifier(**params)

model_xg.fit(X_train, y_train)

y_pred_xg = model_xg.predict(X_test)

In [45]:
accuracy = accuracy_score(y_test, y_pred_xg)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.7821229050279329

In [ ]:
import pandas as pd

new_passenger = pd.DataFrame({
    
    'Sex': [1],     # must match encoding (e.g., male=1, female=0)
    'Age': [22]
    
})

In [ ]:
prediction = model_xg.predict(new_passenger)
print(prediction)